import nodemailer from 'nodemailer';
import { NotificationPayload, NotificationResult, createModuleLogger } from '@boat-monitor/shared';
import fs from 'fs/promises';

const logger = createModuleLogger('EmailChannel');

class EmailChannel {
  private transporter: nodemailer.Transporter | null = null;
  private fromEmail: string;
  private toEmail: string;

  constructor() {
    this.fromEmail = process.env.SMTP_FROM || '';
    this.toEmail = process.env.SMTP_TO || '';

    if (process.env.SMTP_HOST) {
      this.transporter = nodemailer.createTransport({
        host: process.env.SMTP_HOST,
        port: parseInt(process.env.SMTP_PORT || '587', 10),
        secure: process.env.SMTP_SECURE === 'true',
        auth: {
          user: process.env.SMTP_USER,
          pass: process.env.SMTP_PASSWORD
        }
      });
      logger.info('Email transporter initialized');
    } else {
      logger.warn('Email not configured');
    }
  }

  async send(payload: NotificationPayload): Promise<NotificationResult> {
    if (!this.transporter || !this.fromEmail || !this.toEmail) {
      return {
        success: false,
        channel: 'EMAIL' as any,
        error: 'Email not configured'
      };
    }

    try {
      const html = this.formatHtml(payload);
      const attachments: any[] = [];

      // Add screenshot attachment if available
      if (payload.screenshotPath) {
        try {
          const screenshot = await fs.readFile(payload.screenshotPath);
          attachments.push({
            filename: 'screenshot.png',
            content: screenshot,
            contentType: 'image/png'
          });
        } catch (error) {
          logger.warn('Failed to attach screenshot', { error });
        }
      }

      const info = await this.transporter.sendMail({
        from: this.fromEmail,
        to: this.toEmail,
        subject: `[${payload.priority}] ${payload.title}`,
        html,
        attachments
      });

      logger.info('Email notification sent', { messageId: info.messageId });

      return {
        success: true,
        channel: 'EMAIL' as any,
        messageId: info.messageId
      };
    } catch (error) {
      logger.error('Failed to send email notification', { error });
      return {
        success: false,
        channel: 'EMAIL' as any,
        error: error instanceof Error ? error.message : String(error)
      };
    }
  }

  private formatHtml(payload: NotificationPayload): string {
    const priorityColor = {
      INFO: '#3b82f6',
      IMPORTANT: '#f59e0b',
      CRITICAL: '#ef4444'
    };

    const color = priorityColor[payload.priority] || '#3b82f6';

    return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      line-height: 1.6;
      color: #333;
      max-width: 600px;
      margin: 0 auto;
      padding: 20px;
    }
    .header {
      background: ${color};
      color: white;
      padding: 20px;
      border-radius: 8px 8px 0 0;
    }
    .content {
      background: #f9fafb;
      padding: 20px;
      border: 1px solid #e5e7eb;
      border-top: none;
      border-radius: 0 0 8px 8px;
    }
    .button {
      display: inline-block;
      background: ${color};
      color: white;
      padding: 12px 24px;
      text-decoration: none;
      border-radius: 6px;
      margin-top: 20px;
    }
    .metadata {
      background: white;
      padding: 15px;
      border-radius: 6px;
      margin-top: 15px;
    }
    .metadata-item {
      margin: 8px 0;
    }
    .footer {
      text-align: center;
      margin-top: 30px;
      color: #6b7280;
      font-size: 14px;
    }
  </style>
</head>
<body>
  <div class="header">
    <h1 style="margin: 0;">${payload.title}</h1>
    <p style="margin: 10px 0 0 0;">Priority: ${payload.priority}</p>
  </div>
  <div class="content">
    <p>${payload.message}</p>

    ${payload.url ? `
    <a href="${payload.url}" class="button">View Page</a>
    ` : ''}

    <div class="metadata">
      <h3 style="margin-top: 0;">Details</h3>
      ${payload.metadata?.confidence ? `
      <div class="metadata-item">
        <strong>Confidence:</strong> ${Math.round(payload.metadata.confidence * 100)}%
      </div>
      ` : ''}
      ${payload.metadata?.matchedKeywords && payload.metadata.matchedKeywords.length > 0 ? `
      <div class="metadata-item">
        <strong>Matched Keywords:</strong> ${payload.metadata.matchedKeywords.join(', ')}
      </div>
      ` : ''}
      <div class="metadata-item">
        <strong>Time:</strong> ${new Date().toLocaleString('de-DE', { timeZone: 'Europe/Berlin' })}
      </div>
    </div>
  </div>
  <div class="footer">
    <p>Generated by Boat Slip Monitor</p>
    <p><a href="http://localhost:3000">View Dashboard</a></p>
  </div>
</body>
</html>
    `;
  }
}

export const emailChannel = new EmailChannel();
